update
upgrade

# Install Extra Repositories
tap homebrew/binary
tap phinze/cask
# Install Homeinstall-Cask
install brew-cask

# Install system daemons
install dnsmasq

# Install compilers
install apple-gcc42

# Common cui utilities
install readline
install openssl
install gdbm
install pkg-config
install keychain
install mobile-shell
install editorconfig

# lib for build
install pcre
install boost

# langeages
install python --with-brewed-openssl --with-poll --with-dtrace
install ruby --with-doc
install lua --with-completion
install go --cross-compile-all

# programming environmets
install ruby-build
install rbenv
install git --with-brewed-curl --with-brewed-openssl --with-pcre

# basic tools
install mercurial
install --disable-etcdir zsh
install zsh-completions

# gnu tools and some
install coreutils
install gawk
install gnu-sed
install wget
install sl
install tree
install ctags
install wget

# tools
install vim --with-client-server --override-system-vi --with-lua --with-ruby --with-python
#install macvim --with-luajit
install source-highlight
install reattach-to-user-namespace
install tmux
install lynx
install tig

# -- Cask --
cask install iterm2
cask install google-chrome
cask install firefox
cask install vagrant
cask install keyremap4macbook
cask install virtualbox
