# vim:set filetype=zsh :

echo "load MacOSX's private settings ... ..."

alias firefox="/Applications/Firefox.app/Contents/MacOS/firefox"
alias safari="/Applications/Safari.app/Contents/MacOS/Safari"
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"


# 辞書を引く
function dict {
  if [ $# -eq 0 ]; then
    echo "Usage: dict WORD" 1>&2
    return 1
  fi
  open dict://$1
}

function searchword {
  dict $1
  say -v Alex $@
}


echo "done."
